spring.application.name=marine-aquaculture
server.port=${SERVER_PORT:8081}

spring.datasource.url=jdbc:sqlite:./marine_aquaculture.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.datasource.username=
spring.datasource.password=

mybatis-plus.mapper-locations=classpath:mapper/*.xml
mybatis-plus.type-aliases-package=com.backed.entity
mybatis-plus.configuration.map-underscore-to-camel-case=true
mybatis-plus.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl
mybatis-plus.global-config.db-config.id-type=auto

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
